Add check for empty matrix and fix formatting
statisticsnorway/dapla-source-data-processor-build-scripts pull request #17
Opened 2023-11-17 14:21 UTC by Andilun

2023-11-17 14:43 UTC, bjornandre requested changes

2023-11-17 14:43 UTC, bjornandre commented on .github/workflows/kildomaten.yaml
> +            echo "Error: Could not find any sources. This is most likely caused by issue with the structure of your source"
```suggestion
            echo "Error: Could not find any sources for Kildomaten. Please check that you have a folder with the name 'automation/source_data' at the root of your github project."
```

2023-11-17 15:51 UTC, Andilun commented on .github/workflows/kildomaten.yaml
> +            echo "Error: Could not find any sources. This is most likely caused by issue with the structure of your source"
The action won't [trigger](https://github.com/statisticsnorway/dapla-stat-iac/blob/c598b4d2337af9e7732b45a679c049967f691f70/.github/workflows/kildomaten.yaml#L7) unless they have a folder named `automation/source_data`. And Explaining the display_project_name part in an error message might be a bit challenging.

Referring to the dapla manual like you suggested, is probably the best option.

2023-11-19 20:09 UTC, bjornandre approved these changes

2023-11-20 07:43 UTC, merged